name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World"
            echo "Hi, There!"
            echo "flutter"
            echo "dart"
            echo "JavaScript"
            echo "Flutter is Awesome"
      - name: Print goodbye
        run: echo "Done - bye!"
